### ISSUE TITLE
제안서 리뷰 

### ISSUE THREAD

**Issue by MisooKim2** [soungjaeho/C202309-p#1]
1. 양식 내 제공됐던 텍스트는 제거해주세요 (16pt 등)
2. 실시간 알람 기능은 한 학기 배우는 기능으로 구현하기 어려울 것 같아 우려되지만, 학생 역량으로 구현하실 수 있거나, 특정 상황을 가정(미리 시간 정의한다면 관계 없을 것 같습니다
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by Soungtain4** [comment]
네 알겠습니다
